source 'https://github.com/CocoaPods/Specs.git'

platform :ios, 9.0
use_frameworks!

target 'work-life-balance-checker' do
project './work-life-balance-checker.xcodeproj'
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
end
